config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'cats#index'
  resources :users, only: %i[show edit update destroy] do
    resources :likes, only: [:index]
    get 'following', to: 'relationships#index'
  end
  resources :cats, only: %i[new create show edit update destroy] do
    # フォロー関連
    post 'follow' => 'relationships#create'
    delete '/follow' => 'relationships#destroy'
  end
  resources :photos, only: %i[new create show edit update destroy] do
    # いいね関連
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :cat

  with_options presence: true do
    validates :user_id, :cat_id
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_cat, except: [:index]
  before_action :set_follow, except: [:index]

  def index
    @user = User.includes(:following).find(params[:user_id])
    @following = @user.following.page(params[:page]).per(12)
  end

  def create
    follow = Relationship.create(user_id: current_user.id, cat_id: @cat.id)
  end

  def destroy
    follow = Relationship.find_by(user_id: current_user, cat_id: @cat.id)
    follow.delete
  end

  private

  def set_cat
    @cat = Cat.find(params[:cat_id])
  end

  def set_follow
    cat = Cat.find(params[:cat_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user_signed_in? %>
  <% if cat.followed_by?(current_user) %>
    <%= link_to(cat_follow_path(cat), method: :delete, remote: true, id: :"follow-button-#{cat.id}") do %>
      <i class="fa-lg fas fa-star follow-btn"></i>
    <% end %>
  <% else %>
    <%= link_to(cat_follow_path(cat), method: :post, remote: true, id: :"follow-button-#{cat.id}") do %>
      <i class="fa-lg far fa-star follow-btn"></i>
    <% end %>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    <i class="fa-lg far fa-star follow-btn"></i>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$('#follow-button-<%= @cat.id %>').html("<%= escape_javascript(render partial: "relationships/follow", locals: { cat: @cat }) %>");

app/views/relationships/destroy.js.erb
$('#follow-button-<%= @cat.id %>').html("<%= escape_javascript(render partial: "relationships/follow", locals: { cat: @cat }) %>");

app/views/relationships/index.html.erb
<div class="container mt-5">
  <div class="row mt-5 pt-4 mb-5 d-inline">
    <h2 class="text-center">
      <%= link_to @user.user_name, user_path(@user) %>'S FOLLOWING
    </h2>
  </div>
  <% if @following.present? %>
   <div class="row d-flex justify-content-around">
      <% @following.each do |cat| %>
        <div class="col col-6 col-sm-6 col-lg-3 justify-items-center text-center">
          <%= link_to cat_path(cat) do %>
            <%= image_tag cat.icon, class: "rounded-circle", size: "140x140" %>
          <% end %>
          <div class="d-flex flex-row justify-content-center align-items-center p-4">
            <h6 ><%= cat.cat_name %>ちゃん</h6>
            <h6 class="follow-btn pl-1">
              <%= render 'relationships/follow', cat: cat%>
            </h6>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col p-3 m-3 d-flex justify-content-center">
      <%= paginate @following %>
    </div>
  <% else %>
    <div class="text-center">
      <p><%= @user.user_name %>さんはまだねこちゃんをフォローしていないみたいです。</p>
    </div>
  <% end %>
</div>