config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'cats#index'
  resources :users, only: %i[show edit update destroy] do
    resources :likes, only: [:index]
    get 'following', to: 'relationships#index'
  end
  resources :cats, only: %i[new create show edit update destroy] do
    # フォロー関連
    post 'follow' => 'relationships#create'
    delete '/follow' => 'relationships#destroy'
  end
  resources :photos, only: %i[new create show edit update destroy] do
    # いいね関連
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cats, dependent: :destroy
  has_many :photos, dependent: :destroy

  # バリデーション
  validates :user_name, presence: true, length: { minimum: 4, maximum: 32 }
  validates :user_profile, allow_blank: true, length: { maximum: 255 }
  ## パスワードは半角英数字混合での入力が必須
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: VALID_PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください', on: :create

  # いいね関連
  has_many :likes, dependent: :destroy
  has_many :liked_photos, through: :likes, source: :photo

  # フォロー関連
  has_many :relationships
  has_many :following, through: :relationships, source: :cat
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!, except: [:show]
  before_action :user_id_verification, except: [:show]
  before_action :user_params, only: [:update]

  def show
    @cats = @user.cats
    @photos = @user.photos.order('created_at DESC').page(params[:page]).per(6)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @user.destroy
  end

  private

  def set_user
    @user = User.includes(:cats, :photos, :following).find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :user_profile)
  end

  def user_id_verification
    redirect_to root_path unless current_user.id == @user.id
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path(@user), local: true do |f| %>
  <div class="container mt-5">
    <%= render 'shared/error_messages', model: f.object%>
    <div class="row">
      <div class="col">
        <h2 class="text-center">ユーザー情報編集</h2>
      </div>
    </div>
    <div class="row mt-5 justify-content-center">
      <div class="col col-12 col-sm-12 col-lg-6 center-block text-center">
        <div class="field form-group mt-3 mb-4">
          <label for="user_user_name"><h4>ユーザー名</h4></label><span class="badge badge-danger">必須</span><br>
          <span class="form-text text-muted">（4文字以上）</span>
          <%= f.text_field :user_name, autocomplete: "nickname", class: "form-control" %>
        </div>
        <div class="field form-group mb-4">
          <label for="user_user_profile"><h4>プロフィール</h4></label>
          <%= f.text_area :user_profile, autocomplete: "profile", class: "form-control" %>
        </div>
        <div class="actions form-group mt-5 mb-5 d-flex flex-row justify-content-around">
          <div>
            <%= f.submit "OK!", class: "btn btn-lg btn-primary rounded-pill mr-4" %>
          </div>
          <div>
            <%= link_to "DELETE", user_path(@user), method: :delete, data: { confirm: "本当に退会しますか？この操作は取り消せません。" }, class: "btn btn-lg btn-dark rounded-pill" %>
          </div>
        </div>
     <% end %>

app/views/users/show.html.erb
<!--ユーザー情報-->
<div class="container mt-5">
  <div class="row pt-4 mb-5">
    <div class="col col-12 col-sm-12 col-lg-5 mb-3">
      <div class="row">
        <div class="col text-center">
          <h2>PROFILE</h2>
        </div>
      </div>
      <ul class="mb-0">
        <li><h1 class="p-3"><%= @user.user_name %></h1></li>
        <li><h5 class="p-3 text-wrap text-break"><%= @user.user_profile %></h5><li>
        <li>
          <% if user_signed_in? && current_user.id == @user.id %>
            <span class="btn btn-outline-primary rounded-pill"><%= link_to "EDIT", edit_user_path(@user) %></span>
          <% end %>
        </li>
      </ul>
      <div class="d-flex flex-row justify-content-center">
        <div class="p-4">
          <%= link_to user_likes_path(@user) do %>
            <span><i class="fa-lg fas fa-heart like-btn"></i>LIKES</span>
          <% end %>
        </div>
        <div class="p-4">
          <%= link_to user_following_path(@user) do %>
            <span><i class="fa-lg fas fa-star follow-btn"></i>FOLLOWING</span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col col-12 col-sm-12 col-lg-7 mb-3">
      <h2 class="text-center">CATS</h2>
      <% if @cats.present? %>
        <div class="row d-flex flex-row justify-content-between">
            <% @cats.each do |cat| %>
              <div class="col col-6 col-sm-6 col-lg-4 d-flex flex-column justify-content-center mt-4">
                <div class="text-center">
                  <%= link_to cat_path(cat) do %>
                    <%= image_tag cat.icon, class: "rounded-circle", size: "120x120" %>
                  <% end %>
                </div>
                <div class="text-center p-2">
                  <span><%= cat.cat_name %>ちゃん</span>
                  <span><%= render 'relationships/follow', cat: cat %>
                </div>
              </div>
            <% end %>
        </div>
        <% if user_signed_in? && current_user == @user %>
          <div class="text-center pt-2">
            <span class="btn btn-outline-primary rounded-pill">
              <%= link_to "＋NEW CAT", new_cat_path %>
            </span>
          </div>
        <% end %>
      <% else%>
        <div class="row d-flex flex-column text-center">
          <div class="col mt-4">
            <p>まだねこちゃんを登録していないみたいです。</p>
          </div>
          <div class="col">
            <% if user_signed_in? && current_user == @user %>
              <span><%= link_to "ねこちゃんを登録する", new_cat_path %></span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--投稿済み写真-->
<div class="container mt-5">
  <div class="row mt-5 pt-4 d-inline">
    <h2 class="text-center">PHOTOS</h2>
  </div>
  <% if @photos.present? %>
    <div class="row d-flex justify-content-around">
      <% @photos.each do |photo| %>
        <div class="col col-12 col-sm-12 col-lg-5">
            <div class="card border-0">
              <%= link_to photo_path(photo) do %>
                <%= image_tag photo.cat_photo, class: "card-img-top" %>
              <% end %>
              <div class="d-flex flex-row justify-content-between p-2">
                <h6 class="card-title"><%= photo.detail %></h6>
                <div class="like-btn card-text">
                  <%= render 'likes/like', photo: photo %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col p-3 m-3 d-flex justify-content-center">
        <%= paginate @photos %>
      </div>
    </div>
  <% else %>
    <div class="row d-flex flex-column text-center">
      <div class="col mt-4">
        <p>まだねこちゃん写真を投稿していないみたいです。</p>
      </div>
      <div class="col">
        <% if user_signed_in? && current_user == @user %>
          <%= link_to "ねこちゃん写真を投稿する", new_photo_path %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>