config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'cats#index'
  resources :users, only: %i[show edit update destroy] do
    resources :likes, only: [:index]
    get 'following', to: 'relationships#index'
  end
  resources :cats, only: %i[new create show edit update destroy] do
    # フォロー関連
    post 'follow' => 'relationships#create'
    delete '/follow' => 'relationships#destroy'
  end
  resources :photos, only: %i[new create show edit update destroy] do
    # いいね関連
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert text-center">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_nav-bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top justify-content-between p-3">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-brand-link" do %>
      <h1>Nekostagram <i class="fas fa-paw ml-2"></i></h1>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav text-center">
        <% if user_signed_in? %>
          <li class="nav-item p-2"><h5><%= link_to "MY PAGE", user_path(current_user.id), class: "nav-link" %></h5></li>
          <li class="nav-item p-2"><h5><%= link_to "LIKES", user_likes_path(current_user), class: "nav-link" %></h5></li>
          <li class="nav-item p-2"><h5><%= link_to "FOLLOWING", user_following_path(current_user), class: "nav-link" %></h5></li>
          <li class="nav-item p-2"><h5><%= link_to "NEW POST", new_photo_path, class: "nav-link" %></h5></li>
          <li class="nav-item p-2"><h5><%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "nav-link" %></h5></li>
        <% else %>
          <li class="nav-item p-2"><h5><%= link_to "LOG IN", new_user_session_path, class: "nav-link" %></h5></li>
          <li class="nav-item p-2"><h5><%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %></h5></li>
        <% end %>
    </ul>
  </div>
</nav>