config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'cats#index'
  resources :users, only: %i[show edit update destroy] do
    resources :likes, only: [:index]
    get 'following', to: 'relationships#index'
  end
  resources :cats, only: %i[new create show edit update destroy] do
    # フォロー関連
    post 'follow' => 'relationships#create'
    delete '/follow' => 'relationships#destroy'
  end
  resources :photos, only: %i[new create show edit update destroy] do
    # いいね関連
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
end

app/models/cat.rb
# frozen_string_literal: true

class Cat < ApplicationRecord
  has_many :cat_photos, dependent: :destroy
  has_many :photos, through: :cat_photos
  belongs_to :user
  has_one_attached :icon

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :cat_sex
  belongs_to :cat_breed

  with_options numericality: { other_than: 1, message: 'を選んでください' } do
    validates :cat_sex_id, :cat_breed_id
  end

  validates :cat_name, presence: true
  validates :icon, presence: { message: 'を選んでください' }

  validates :cat_age, numericality: { only_integer: true }, allow_blank: true

  # フォロー関連
  has_many :relationships
  has_many :followers, through: :relationships, source: :user

  def followed_by?(user)
    relationships.where(user_id: user.id).exists?
  end
end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_cat, only: %i[show edit update destroy]
  before_action :user_id_verification, only: %i[edit update destroy]

  def index
    @photos = Photo.includes(:cats).order('created_at DESC').limit(24)
    @cats = Cat.order('created_at DESC').limit(12)
    if user_signed_in? && current_user.following.present?
      @user = User.includes(:following).find(current_user.id)
      @following_cats = @user.following.includes(:photos)
      @following_cats_photos = Photo.joins(:cat_photos).where("cat_photos.cat_id":  @following_cats.map(&:id)).order('created_at DESC').limit(6)
    end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_path(@cat)
    else render :new
    end
  end

  def show
    @photos = @cat.photos.order('created_at DESC').page(params[:page]).per(9)
  end

  def edit; end

  def update
    if @cat.update(cat_params)
      redirect_to cat_path
    else render :edit
    end
  end

  def destroy
    @user = @cat.user
    @cat.destroy
    redirect_to user_path(@user)
  end

  private

  def cat_params
    params.require(:cat).permit(:cat_name, :cat_age, :cat_sex_id, :cat_breed_id, :icon).merge(user_id: current_user.id)
  end

  def set_cat
    @cat = Cat.includes(:user, :photos).find(params[:id])
  end

  def user_id_verification
    redirect_to root_path unless current_user.id == @cat.user_id
  end
end

app/helpers/cats_helper.rb
# frozen_string_literal: true

module CatsHelper
end

app/views/cats/edit.html.erb
<%= form_with model: @cat, url: cat_path(@cat), local: true do |f| %>
  <div class="container mt-5">
    <%= render 'shared/error_messages', model: f.object%>
    <div class="row">
      <div class="col">
        <h2 class="text-center">EDIT CAT</h4>
      </div>
    </div>
    <div class="row mt-5 justify-content-center">
      <div class="col col-12 col-sm-12 col-lg-6 center-block text-center">
        <div class="form-group mb-4">
          <label for="cat_cat_name"><h4>おなまえ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.text_field :cat_name, maxlength:"40", class: "form-control" %>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_age"><h4>ねんれい</h4><span class="badge badge-secondary">数字のみ</span></label>
          <%= f.text_field :cat_age, class: "form-control" %>
          <span class="form-text text-muted">
            ※1才未満は0で記入してください。
          </span>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_sex_id"><h4>せいべつ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.collection_select(:cat_sex_id, CatSex.all, :id, :name, {}, {class: "form-control"}) %>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_breed_id"><h4>ひんしゅ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.collection_select(:cat_breed_id, CatBreed.all, :id, :name, {}, {class: "form-control"}) %>
        </div>
        <div class="form-group mb-4">
          <label for="cat_icon"><h4>おしゃしん</h4></label><span class="badge badge-danger">必須</span>
          <%= f.file_field :icon, class: "form-control" %>
        </div>
        <div class="form-group mt-5 mb-5 d-flex flex-row justify-content-around">
          <div>
            <%= f.submit "OK!", class: "btn btn-lg btn-primary rounded-pill mr-4" %>
          </div>
          <div>
            <%= link_to "DELETE", cat_path(@cat), method: :delete, data: { confirm: "本当に削除しますか？この操作は取り消せません。" }, class: "btn btn-lg btn-dark rounded-pill" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/cats/index.html.erb
<!--新着写真（フォロー）-->
<% if @following_cats.present? %>
  <div class="container mt-5">
    <div class="row mt-5 pt-4 mb-5">
      <div class="col text-center">
        <h2>FOLLOWING'S NEW PHOTOS</h2>
      </div>
    </div>
    <% if @following_cats_photos.present? %>
      <div class="row d-flex justify-content-around">
        <% @following_cats_photos.each do |photo| %>
          <div class="col col-12 col-sm-12 col-lg-3 mb-3">
              <div class="card border-0">
                <%= link_to photo_path(photo) do %>
                  <%= image_tag photo.cat_photo, class: "card-img-top" %>
                <% end %>
                <div class="d-flex flex-row   justify-content-between p-2">
                  <h5 class="card-title"><%= photo.detail %></h5>
                  <div class="like-btn card-text">
                    <%= render 'likes/like', photo: photo %>
                  </div>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="text-center">
        <p>フォローしているねこちゃんはまだ写真が投稿されていないみたいです。</p>
      </div>
    <% end %>
  </div>
<% end %>

<!--新着写真-->
<div class="container mt-5">
  <div class="row mt-5 pt-4 mb-5 d-inline">
    <h2 class="text-center"> NEW PHOTOS</h2>
  </div>
  <div class="row d-flex justify-content-around">
    <% if @photos.present? %>
      <% @photos.each do |photo| %>
        <div class="col col-12 col-sm-12 col-lg-4 mb-3">
            <div class="card border-0">
              <%= link_to photo_path(photo) do %>
                <%= image_tag photo.cat_photo, class: "card-img-top" %>
              <% end %>
              <div class="d-flex flex-row justify-content-between p-2">
                <h5 class="card-title"><%= photo.detail %></h5>
                <div class="like-btn card-text">
                  <%= render 'likes/like', photo: photo %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    <% else %>
      まだ誰もねこちゃん写真を投稿していないようです。
      <% if user_signed_in? %>
        <% if current_user.cats.exists? %>
          <%= link_to "ねこちゃん写真を投稿する", new_photo_path %>
        <% else %>
          <%= link_to "新しくねこちゃんを登録する", new_cat_path %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<!--新着ねこちゃん-->
<div class="container mt-5">
  <div class="row mt-5 pt-4 d-inline">
    <h2 class="text-center">NEW CATS</h2>
  </div>
  <div class="row d-flex justify-content-around">
    <% if @cats.present? %>
      <% @cats.each do |cat| %>
        <div class="col col-6 col-sm-6 col-lg-4 justify-items-center text-center">
          <%= link_to cat_path(cat) do %>
            <%= image_tag cat.icon, class: "rounded-circle", size: "140x140" %>
          <% end %>
          <div class="d-flex flex-row justify-content-center align-items-center p-4">
            <h5 ><%= cat.cat_name %></h6>
            <h5 class="follow-btn pl-1">
              <%= render 'relationships/follow', cat: cat%>
            </h5>
          </div>
        </div>
      <% end %>
    <% else %>
      まだねこちゃんが登録されていないようです。
    <% end %>
  </div>
</div>

app/views/cats/new.html.erb
<%= form_with model: @cat, url: cats_path, local: true do |f| %>
  <div class="container mt-5">
    <%= render 'shared/error_messages', model: f.object%> 
    <div class="row">
      <div class="col">
        <h2 class="text-center">NEW CAT</h2>
      </div>
    </div>
    <div class="row mt-5 justify-content-center">
      <div class="col col-12 col-sm-12 col-lg-6 center-block text-center">
        <div class="form-group mb-4">
          <label for="cat_cat_name"><h4>おなまえ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.text_field :cat_name, maxlength:"40", class: "form-control" %>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_age"><h4>ねんれい</h4></label><span class="badge badge-secondary">半角数字のみ</span>
          <%= f.text_field :cat_age, class: "form-control" %>
          <span class="form-text text-muted">
            ※1才未満は0で記入してください。
          </span>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_sex_id"><h4>せいべつ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.collection_select(:cat_sex_id, CatSex.all, :id, :name, {}, {class: "form-control"}) %>
        </div>
        <div class="form-group mb-4">
          <label for="cat_cat_breed_id"><h4>ひんしゅ</h4></label><span class="badge badge-danger">必須</span>
          <%= f.collection_select(:cat_breed_id, CatBreed.all, :id, :name, {}, {class: "form-control"}) %>
        </div>
        <div class="form-group">
          <label for="cat_icon"><h4>おしゃしん</h4></label><span class="badge badge-danger">必須</span>
          <%= f.file_field :icon, class: "form-control" %>
        </div>
        <div class="form-group mt-5">
          <%= f.submit "OK!", class: "btn btn-lg btn-primary rounded-pill" %>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/cats/show.html.erb
<div class="container mt-5">
  <div class="row d-flex flex-row align-items-start justify-content-between">
    <div class="col col-12 col-sm-12 col-lg-4 block-center">
      <div class="row">
        <div class="col">
          <h2 class="text-center"><%= @cat.cat_name%></h2>
        </div>
      </div>
      <div class="row d-flex flex-column text-center">
        <div class="col mt-3 mb-2">
          <%= image_tag @cat.icon, class: "rounded-circle", size: "140x140" %>
        </div>
        <div class="col">
          <%= render 'relationships/follow', cat: @cat %>
        </div>
      </div>
      <div class="mx-auto">
          <ul class="mt-4 text-left">
            <li><%= link_to "#{@cat.user.user_name}さん", user_path(@cat.user) %>ちのねこちゃん
            <li>品種 <%= @cat.cat_breed.name %>
            <li>性別 <%= @cat.cat_sex.name %>
            <% if @cat.cat_age.present? %>
              <li>年齢 <%= @cat.cat_age %>さい
            <% end %>
            <% if user_signed_in? && current_user.id == @cat.user_id%>
              <li class="text-center"><span class="btn btn-outline-primary rounded-pill mt-3"><%= link_to "EDIT", edit_cat_path(@cat) %></span>
            <% end %>
          </ul>
      </div>
    </div>
    <div class="col col-12 col-sm-12 col-lg-8 block-center">
      <div class="row">
        <div class="col">
          <h2 class="text-center mb-5">PHOTOS</h2>
        </div>
      </div>
      <% if @photos.present? %>
        <div class="row d-flex flex-row ">
          <% @photos.each do |photo| %>
            <div class="col col-12 col-sm-12 col-lg-4 mb-3">
              <div class="card border-0">
                <%= link_to photo_path(photo) do %>
                  <%= image_tag photo.cat_photo, class: "card-img-top" %>
                <% end %>
                <div class="d-flex flex-row   justify-content-between p-2">
                  <h6 class="card-title"><%= photo.detail %></h6>
                  <div class="like-btn card-text">
                    <%= render 'likes/like', photo: photo %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col p-3 m-3 d-flex justify-content-center">
            <%= paginate @photos %>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col text-center">
            <span>まだ何も投稿されていないようです。</span>
            <% if user_signed_in? && @cat.user_id == current_user.id %><br>
              <span class="btn btn-primary mt-3"><%= link_to "写真を投稿する", new_photo_path %></span>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>